### ISSUE TITLE
Maybe you are blocked by your previous post on weibo

### ISSUE THREAD

**Issue by chucklu** [cyanzhong/apple-terminated-my-dev-account#1]
https://weibo.com/1765732340/I0jO7nYgS?from=page_1005051765732340_profile&wvr=6&mod=weibotime
![image](https://user-images.githubusercontent.com/3004057/63639724-87c3e800-c6c9-11e9-9e75-67ab35bc7fb9.png)

**Comment by 77xi** [comment]
微博上说已经解封了
