### ISSUE TITLE
Apple is junk.

### ISSUE THREAD

**Issue by falstack** [cyanzhong/apple-terminated-my-dev-account#2]
原本我也有一些想吐槽的东西，当时并没有说出来，毕竟事情已经那样无济于事了，不过还是想借这里说出来。

我认为 Apple 的 toC 业务做的非常好，产品受人尊敬，但是 toB 业务就是一坨屎。

特别对于我们这些开发者， Apple 总是在审判我们，他们认为是什么那就是什么，完全不理睬我们的回复。

18年的时候，我和朋友一起开发了一款 iOS APP，它的源码在这里：[calibur-iOS](https://github.com/calibur-tv/Geass)

因为我们是业余的时间在做，并且开发人数有限，所以打算把最简单的功能做出来之后，再慢慢迭代。当时网站已经有8万的注册用户，很多人都在等 iOS 版上线（Android 早就上线了）。

当我们终于开发出一个 release 版本后，提交 iOS 审核，然后噩梦就开始了。

![image](https://user-images.githubusercontent.com/16357724/63641204-e5adfb00-c6dc-11e9-8812-e5e3cca96ca8.png)

第一次提交审核，不通过。
为什么不通过，我不知道。
因为 Apple 的审核人员不会告诉我为什么不通过！
然后让我们改好，不然不给通过，但怎么改，不知道。
于是我只好在 Apple 的开发者网页那边去给审核员反馈，问到底发生了什么事。
然后令人震惊的是，一次回信，需要等待一周时间。
一周过后，审核员会像机器人一样把你被拒绝的“理由”复述一遍。
是的，你还是不知道你为什么被拒绝，只是被重复告知“我们拒绝了你，请修复好你的APP”。

然后我又反馈去询问到底是「什么地方出了问题？是否可以告诉我们，以便我们改正」。
得到的结果依然是“复读”。

没办法，只好去向 Apple 的审核委员会去举报，举报之后在下周的某个工作日，我就会收到来自美国的电话，与我沟通。

这之后发生的事情依然很恶心，与我沟通的员工听着不是大陆人，然后带着蜜汁自信对我各种刁难，最后告诉我：“您的APP与应用市场上的其它APP是相同的，我们怀疑您抄袭，所以您被拒绝了”。

我？？？？

“那么请问那个APP是什么，我可以去看看吗？”

“不可以，那个APP因为违规已经被下架了。”

我？？？？

“我们的APP是自己开发的，代码在 Github 的开源仓库，你们可以去审查，我们并没有抄袭。”

“但是我们的审核结果就是你们的APP是抄袭”

我？？？？

“那好，我看审核信息里面说要我们改，我们要怎么改才行？”

“对不起，我们不能透露给你其它开发者开发的 APP 的信息。”

“其他开发者开发 APP 就是希望被人使用，你告诉我们这些信息会有问题吗？”

“对不起，那个开发者账号因为违规已经被我们封禁了，所以我们不能透露他的信息。”

我？？？？

“那你们能认为我们的APP与他的APP相似，那么肯定是做过对比的吧，起码给我个截图或者录个视频？”

“稍候我们会提供的，请问您还有什么别的事吗？”

“没有了谢谢。”

然后，她没有给我任何东西。

--------

在无数次的重新提交审核之后，导致的问题就是审核的权重被压的越来越低，审核速度越来越慢。

在后来，也在后台经过了无数次的反馈，最终知道了审核不通过的原因：

我们的 App 叫 calibur，与另一块在中国大陆未发售的游戏重名了，因此被拒绝审核。

我？？？？

那个和我沟通的那位审核员，为什么与现在我得到的反馈结果说的不一样？

我很气，但没办法，我只能继续改，换名字，再提审。

然后还是不通过。为什么，因为我们的UI设计和其它APP很像。

抱歉，这个业余开发的 APP 并没有设计，艹。

再问是什么 UI 设计与其它 APP 冲突了，于是开始了无数次的“复读”，复读同样的条款给我。

我恳求式的问“到底是哪里不一样，请告诉我们，这样有助于我们改善“。

对不起，你不会被告知任何东西！艹。

----------

无奈之下只能再次想 Apple 审核委员会投诉，于是我又与那位审核员通了一次电话。

可以说很不愉快，因为她根本就不是来与我沟通的，而是来”宣读圣旨“，告诉我：
”这个APP是违规的，我们不会通过的，你们也不要换其他账号重复上传，照样不会通过的！“

语言中透露着嘲讽，用她那高高在上的态度宣判我们做了好几个月的 APP 死刑。

艹。

后来我的 APP 再也没能上线，我受够了。

----------

在写这个内容的时候，我正在给阿里云提工单，现在是凌晨两点半，并且有人一直回复我。

腾讯的很多东西做的垃圾，但是我只要找到人工客服的入口，每天早上9：30我去人工反馈，一定有人理我，和我说话，解决问题。

----------

我用着  Mac 电脑，IPhone 手机，喜欢着 Apple 的产品，但身为开发者，我真的感觉 Apple 的服务就是垃圾。

如果本文引起你的不适，那么对不起。

**Comment by KKFantasy** [comment]
同样因为名称相似被拒绝过，个把月的工作付之东流。苹果傲慢的态度令人不适。

**Comment by Nathanlee2010** [comment]
虽然我还没有开始我的ios项目计划，但是看了你的描述，苹果真的是太烂了！让开发者寒心！

**Comment by WuHuaJi0** [comment]
看了你的经历，为你感到气愤，苹果真是傲慢！

**Comment by zj299792458** [comment]
建议放上app界面截图以及 苹果 拒绝详情截图会更有说服力 ，毕竟现在一面之词说得再好已经不敢 轻信……

**Comment by Lessica** [comment]
苹果向来不是很欢迎不能给他们带来营收的业余 App

**Comment by fairytale110** [comment]
就是因为有消费者和开发者这样惯着它，它才这么嚣张

**Comment by wlgemini** [comment]
真tm气人啊，想好好沟通，对面都不说句人话！

**Comment by gethin94** [comment]
苹果到现在好像没有拿到5G，市场份额估计要被压缩了

**Comment by falstack** [comment]
![image](https://user-images.githubusercontent.com/16357724/63704535-d904e080-c85d-11e9-9506-9c1c30f588b4.png)

![image](https://user-images.githubusercontent.com/16357724/63704550-defac180-c85d-11e9-8eae-851723f7d644.png)

![image](https://user-images.githubusercontent.com/16357724/63704552-e15d1b80-c85d-11e9-9b1b-535972081faf.png)

![image](https://user-images.githubusercontent.com/16357724/63704557-e4580c00-c85d-11e9-839a-7eb6a701eb8b.png)

![image](https://user-images.githubusercontent.com/16357724/63704559-e752fc80-c85d-11e9-9d7d-6b9604782dd1.png)

![image](https://user-images.githubusercontent.com/16357724/63704564-e9b55680-c85d-11e9-8219-0e1ec0de3e37.png)

![image](https://user-images.githubusercontent.com/16357724/63704572-ed48dd80-c85d-11e9-820a-46a1ef21b94a.png)


![image](https://user-images.githubusercontent.com/16357724/63704587-f3d75500-c85d-11e9-8c61-e8bfc38d63a2.png)


![image](https://user-images.githubusercontent.com/16357724/63704594-f76adc00-c85d-11e9-9978-85b1dcd21bcb.png)


![image](https://user-images.githubusercontent.com/16357724/63704600-fa65cc80-c85d-11e9-956c-cd765ba63d0e.png)

![image](https://user-images.githubusercontent.com/16357724/63704617-fd60bd00-c85d-11e9-8232-a899bf15cf07.png)

@zj299792458  你要的聊天记录的一部分，这是最后我已经很生气了的截图，前面的几个会话从2月份开始就已经是在重复了。

中间是打过两次电话的。

我还是补充一下吧，我认为 APPLE 这样的公司是有傲慢的资本的，毕竟做的这么好。
但我不明白 APPLE 的审核员到底有什么傲慢的资本。
审核员是服务者，本是解决问题的，但到了我这里，他们成了复读机和宣读判决的人。

另外就是，好像直至现在，我去做一个 iOS APP 也无法知道这个名字是否在其它国家地区是已经使用过的，如果我和他们的名字重复，那我就会被判定为蹭热度，然后被打回。

但你这个APP名称又不强校验成 unique？我不知道这是什么操作。

**Comment by cksa** [comment]
为什么你们那么喜欢开发apple应用呢？很赚钱吗？

**Comment by zj299792458** [comment]
@falstack 同情，问下你们这个界面是自己设计的嘛？还是外包的，或者是某框架集成的？苹果只说了和某个被封的账户提交的应用很像，确实很霸道

**Comment by falstack** [comment]
@zj299792458 自己设计的，设计稿的原型图也发给 APPLE 审核员，但是没用的，他们说了算。

但到最后，我都不知道我是和哪个 APP 在设计上冲突了，冲突了哪个地方，因为我无权知道。

**Comment by falstack** [comment]
与APPLE审核员的聊天截图我删了，因为条款里面要求这些东西是不能公开的。
